spring.application.name=civix
spring.datasource.url=jdbc:postgresql://localhost:5432/db_civix
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.root=INFO
logging.level.com.civix=DEBUG
logging.file.name=logs/api.log

ip.frontend=http://localhost:4200
jwt.secret=fax/5z+9d10k7zW/FAWOmez2J+vokXbEkNjbRzTJNKFQDAet+GESCtnIezISRIV/05BYIjPQYbwQiIdesnpSSA==
jwt.expiration-ms=4800000
